# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dine-O' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dine-O

  pod 'Alamofire'

  target 'Dine-OTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dine-OUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
